'use strict';

const HISTORY_VERSION = '15.0.0';
const SESSION_LENGTH = 10;
const state = { topic:'maps', questionIndex:0, currentQuestionId:null, score:0, streak:0, attempts:0, answered:false, processing:false, questions:[] };
const topics = [
  { key:'maps', icon:'🗺️', title:'Mapas y ubicación', subtitle:'Puntos cardinales, mapas y continentes' },
  { key:'climate', icon:'🌦️', title:'Clima y paisajes', subtitle:'Zonas, paisajes y adaptación' },
  { key:'ancient', icon:'🏛️', title:'Grecia y Roma', subtitle:'Vida cotidiana y legado' },
  { key:'society', icon:'🏘️', title:'Vida en sociedad', subtitle:'Comunidad, normas y convivencia' },
  { key:'citizenship', icon:'🤝', title:'Ciudadanía', subtitle:'Derechos, responsabilidades y respeto' },
  { key:'review', icon:'⭐', title:'Repaso mixto', subtitle:'Un poco de todo' },
];
const els = {
  home:document.querySelector('#historyHome'), quiz:document.querySelector('#historyQuiz'), result:document.querySelector('#historyResult'), grid:document.querySelector('#historyTopicGrid'),
  stars:document.querySelector('#historyStars'), sessions:document.querySelector('#historySessions'), bestStreak:document.querySelector('#historyBestStreak'), back:document.querySelector('#historyBackButton'),
  modeLabel:document.querySelector('#historyModeLabel'), counter:document.querySelector('#historyCounter'), prompt:document.querySelector('#historyPrompt'), question:document.querySelector('#historyQuestion'),
  answers:document.querySelector('#historyAnswers'), feedback:document.querySelector('#historyFeedback'), next:document.querySelector('#historyNextButton'), streak:document.querySelector('#historyStreak'),
  resultEmoji:document.querySelector('#historyResultEmoji'), resultTitle:document.querySelector('#historyResultTitle'), resultText:document.querySelector('#historyResultText'), finalScore:document.querySelector('#historyFinalScore'),
  again:document.querySelector('#historyAgainButton'), homeButton:document.querySelector('#historyHomeButton'),
};
function assertElements(){const missing=Object.entries(els).filter(([,v])=>!v).map(([k])=>k);if(missing.length)throw new Error(`Faltan elementos de Historia: ${missing.join(', ')}`);}
function loadProgress(){try{const v=JSON.parse(localStorage.getItem('antoniaHistoryProgress')||'{}');return v&&typeof v==='object'?v:{};}catch{return{};}}
const progress=loadProgress(); progress.stars=Number.isFinite(progress.stars)?progress.stars:0; progress.sessions=Number.isFinite(progress.sessions)?progress.sessions:0; progress.bestStreak=Number.isFinite(progress.bestStreak)?progress.bestStreak:0; progress.byTopic=progress.byTopic&&typeof progress.byTopic==='object'?progress.byTopic:{};
function saveProgress(){try{localStorage.setItem('antoniaHistoryProgress',JSON.stringify(progress));}catch{}renderProgress();}
function renderProgress(){els.stars.textContent=String(progress.stars);els.sessions.textContent=String(progress.sessions);els.bestStreak.textContent=String(progress.bestStreak);}
function show(view){[els.home,els.quiz,els.result].forEach(v=>v.classList.remove('active'));view.classList.add('active');window.scrollTo(0,0);}
function shuffle(items){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
let serial=0;
function q(prompt,display,correct,options,explanation,reading=false){const c=String(correct);const unique=[];[c,...options.map(String)].forEach(v=>{if(!unique.includes(v))unique.push(v);});if(!prompt||!display||!c||unique.length<2)throw new Error('Pregunta de Historia inválida');return{id:`his-${Date.now()}-${++serial}`,prompt,display,correct:c,options:shuffle(unique),explanation,reading};}
const banks={
  maps:[
    q('¿Qué punto cardinal está arriba en la mayoría de los mapas?', '🧭', 'norte', ['norte','sur','este','oeste'], 'En la mayoría de los mapas, el norte se representa hacia arriba.'),
    q('Si miras al norte, ¿qué punto cardinal queda a tu derecha?', 'NORTE ↑', 'este', ['este','oeste','sur','norte'], 'Si miras al norte, el este queda a la derecha.'),
    q('¿Qué herramienta representa lugares desde arriba?', 'Ubicación', 'un mapa', ['un mapa','una receta','una canción','un termómetro'], 'Un mapa representa un territorio visto de forma simplificada desde arriba.'),
    q('¿Para qué sirve una leyenda en un mapa?', '🗺️', 'explica el significado de símbolos y colores', ['explica el significado de símbolos y colores','mide la temperatura','cuenta habitantes automáticamente','marca la hora'], 'La leyenda explica qué significan los símbolos del mapa.'),
    q('¿Qué línea imaginaria divide la Tierra en hemisferio norte y sur?', '🌍', 'el ecuador', ['el ecuador','el meridiano de Greenwich','el trópico solamente','la cordillera'], 'El ecuador divide la Tierra en hemisferio norte y sur.'),
    q('¿Cuál es un continente?', 'Elige uno', 'América', ['América','Pacífico','Andes','Santiago'], 'América es un continente.'),
    q('¿Cuál es un océano?', 'Elige uno', 'Pacífico', ['Pacífico','Europa','África','Andes'], 'El Pacífico es un océano.'),
    q('¿Qué indica una escala en un mapa?', 'Escala', 'la relación entre distancia del mapa y distancia real', ['la relación entre distancia del mapa y distancia real','la temperatura del lugar','el nombre del autor','la edad del mapa'], 'La escala ayuda a interpretar distancias reales.'),
    q('Si un lugar está al oeste de otro, ¿hacia qué lado suele aparecer en un mapa?', 'Norte arriba', 'a la izquierda', ['a la izquierda','a la derecha','siempre arriba','siempre abajo'], 'Con norte arriba, el oeste queda a la izquierda.'),
    q('¿Para qué sirve una brújula?', '🧭', 'para orientarse con los puntos cardinales', ['para orientarse con los puntos cardinales','para medir masa','para escribir mapas','para medir lluvia'], 'La brújula ayuda a orientarse usando los puntos cardinales.'),
  ],
  climate:[
    q('¿Qué describe el clima de un lugar?', 'Clima', 'condiciones habituales durante largos períodos', ['condiciones habituales durante largos períodos','solo lo que pasa esta hora','el nombre de sus calles','la cantidad de escuelas'], 'El clima describe condiciones frecuentes durante períodos largos.'),
    q('¿Qué paisaje suele tener poca lluvia?', 'Paisajes', 'desierto', ['desierto','selva húmeda','bosque lluvioso','pantano'], 'Los desiertos reciben muy poca precipitación.'),
    q('¿Qué ropa ayuda en un lugar muy frío?', '❄️', 'ropa abrigada', ['ropa abrigada','traje de baño solamente','sandalias siempre','ninguna ropa'], 'La ropa abrigada ayuda a conservar el calor corporal.'),
    q('¿Qué puede influir en el clima?', 'Factores del clima', 'latitud y altura', ['latitud y altura','el nombre de una calle','el color de las casas','el idioma'], 'La latitud y la altura influyen en las temperaturas y el clima.'),
    q('¿Qué característica tiene una zona tropical?', '🌴', 'temperaturas altas gran parte del año', ['temperaturas altas gran parte del año','hielo todo el año','sin luz solar','temperaturas siempre bajo cero'], 'Las zonas tropicales suelen ser cálidas gran parte del año.'),
    q('¿Qué acción muestra adaptación humana al ambiente?', 'Vivir en un lugar lluvioso', 'usar techos que evacúen el agua', ['usar techos que evacúen el agua','ignorar la lluvia','quitar todos los caminos','vivir sin refugio'], 'Las personas adaptan viviendas y costumbres a las condiciones del lugar.'),
    q('¿Qué paisaje tiene abundantes árboles?', '🌳', 'bosque', ['bosque','desierto','océano','glaciar'], 'Un bosque se caracteriza por abundancia de árboles.'),
    q('¿Qué instrumento usamos para medir temperatura?', 'Tiempo y clima', 'termómetro', ['termómetro','brújula','regla','mapa'], 'El termómetro mide temperatura.'),
    q('¿Qué es una precipitación?', 'Clima', 'agua que cae de la atmósfera', ['agua que cae de la atmósfera','viento solamente','luz solar','una montaña'], 'La lluvia, nieve y granizo son tipos de precipitación.'),
    q('¿Por qué las personas construyen de manera diferente según el lugar?', 'Adaptación', 'para responder al clima y al ambiente', ['para responder al clima y al ambiente','porque todas las casas deben ser iguales','para evitar mapas','para cambiar el continente'], 'Las construcciones pueden adaptarse al frío, calor, lluvia, viento y otros factores.'),
  ],
  ancient:[
    q('¿En qué región surgió la antigua civilización griega?', 'Grecia antigua', 'en torno al mar Mediterráneo', ['en torno al mar Mediterráneo','en América del Sur','en Oceanía','en la Antártica'], 'La civilización griega se desarrolló en torno al mar Mediterráneo.'),
    q('¿Qué eran las polis griegas?', '🏛️', 'ciudades-estado', ['ciudades-estado','ríos','barcos','monedas'], 'Las polis eran ciudades-estado con organización propia.'),
    q('¿Qué ciudad griega se asocia con el desarrollo de la democracia?', 'Grecia antigua', 'Atenas', ['Atenas','Roma','Cartago','Alejandría'], 'Atenas es conocida por desarrollar formas tempranas de democracia.'),
    q('¿Qué actividad era importante en Grecia por su cercanía al mar?', '🌊', 'navegación y comercio', ['navegación y comercio','minería lunar','aviación','ferrocarriles'], 'El mar favoreció la navegación y el comercio entre ciudades.'),
    q('¿Dónde surgió la antigua civilización romana?', 'Roma antigua', 'en la península itálica', ['en la península itálica','en Australia','en Chile central','en Japón'], 'Roma surgió en la península itálica.'),
    q('¿Qué construían los romanos para transportar agua?', 'Ingeniería romana', 'acueductos', ['acueductos','rascacielos','aeropuertos','satélites'], 'Los acueductos llevaban agua hacia ciudades y poblados.'),
    q('¿Qué lengua usaban los romanos y dejó gran influencia?', 'Roma', 'latín', ['latín','inglés moderno','quechua','mapudungun'], 'El latín influyó en muchas lenguas actuales, incluido el español.'),
    q('¿Qué tenían en común griegos y romanos?', 'Comparar', 'desarrollaron ciudades, leyes y vida pública', ['desarrollaron ciudades, leyes y vida pública','usaban teléfonos móviles','viajaban en avión','vivían solo en cuevas'], 'Ambas civilizaciones tuvieron ciudades, instituciones y formas de vida pública.'),
    q('¿Cuál es un legado de Grecia antigua?', 'Legados', 'teatro y pensamiento filosófico', ['teatro y pensamiento filosófico','internet','automóviles','electricidad doméstica'], 'El teatro y la filosofía son legados asociados a Grecia antigua.'),
    q('¿Cuál es un legado de Roma antigua?', 'Legados', 'derecho y obras públicas', ['derecho y obras públicas','televisión','aviones','computadores'], 'El derecho romano y sus obras de ingeniería tuvieron gran influencia.'),
  ],
  society:[
    q('¿Qué es una comunidad?', 'Vida en sociedad', 'un grupo de personas que comparte un espacio o vínculos', ['un grupo de personas que comparte un espacio o vínculos','un solo objeto','un tipo de clima','una montaña'], 'Una comunidad está formada por personas que comparten un entorno o relaciones.'),
    q('¿Para qué sirven las normas?', 'Convivencia', 'para organizar la convivencia y cuidarnos', ['para organizar la convivencia y cuidarnos','para impedir toda conversación','para elegir el clima','para cambiar mapas'], 'Las normas ayudan a convivir de manera segura y respetuosa.'),
    q('¿Qué es una institución de la comunidad?', 'Ejemplo', 'una escuela', ['una escuela','una nube','un río','una roca'], 'Una escuela es una institución que cumple funciones en la comunidad.'),
    q('¿Qué acción favorece la convivencia?', 'En el curso', 'escuchar cuando otra persona habla', ['escuchar cuando otra persona habla','interrumpir siempre','romper materiales','burlarse'], 'Escuchar demuestra respeto y facilita la convivencia.'),
    q('¿Qué servicio presta un hospital?', 'Comunidad', 'atención de salud', ['atención de salud','venta de mapas','pronóstico del tiempo únicamente','transporte aéreo'], 'Los hospitales entregan atención de salud.'),
    q('¿Qué servicio presta una municipalidad?', 'Comunidad', 'gestiona asuntos y servicios locales', ['gestiona asuntos y servicios locales','controla todos los países','mide la edad de las personas','crea continentes'], 'La municipalidad administra y coordina servicios de la comuna.'),
    q('¿Qué significa colaborar?', 'Trabajo en grupo', 'trabajar con otros para lograr una meta', ['trabajar con otros para lograr una meta','hacer todo sin escuchar','evitar responsabilidades','romper acuerdos'], 'Colaborar es aportar junto a otras personas.'),
    q('¿Qué ayuda a resolver un conflicto?', 'Convivencia', 'dialogar y buscar acuerdos', ['dialogar y buscar acuerdos','gritar más fuerte','ignorar siempre','golpear'], 'El diálogo permite escuchar y buscar soluciones respetuosas.'),
    q('¿Qué es un espacio público?', 'Ejemplo', 'una plaza', ['una plaza','un dormitorio particular','un cuaderno personal','un clóset'], 'Una plaza es un espacio de uso compartido por la comunidad.'),
    q('¿Por qué cuidamos los espacios públicos?', 'Bien común', 'porque son usados por muchas personas', ['porque son usados por muchas personas','porque pertenecen a una sola persona','porque no sirven','porque nadie los usa'], 'Cuidarlos beneficia a toda la comunidad.'),
  ],
  citizenship:[
    q('¿Qué es un derecho?', 'Ciudadanía', 'algo que protege la dignidad y bienestar de las personas', ['algo que protege la dignidad y bienestar de las personas','una orden para molestar','un premio solo para adultos','una regla de un juego'], 'Los derechos protegen condiciones fundamentales para vivir con dignidad.'),
    q('¿Cuál es un derecho de niñas y niños?', 'Elige uno', 'recibir educación', ['recibir educación','ser obligados a trabajar siempre','no recibir cuidados','ser discriminados'], 'Niñas y niños tienen derecho a la educación.'),
    q('¿Cuál es una responsabilidad en la escuela?', 'Convivencia', 'cuidar materiales y respetar a otros', ['cuidar materiales y respetar a otros','romper libros','insultar','ignorar todas las normas'], 'Responsabilidades y derechos ayudan a convivir mejor.'),
    q('¿Qué significa respetar una opinión diferente?', 'Diálogo', 'escuchar sin burlarse ni agredir', ['escuchar sin burlarse ni agredir','obligar al otro a pensar igual','interrumpir siempre','reírse de la persona'], 'Respetar no significa estar de acuerdo, sino tratar al otro con dignidad.'),
    q('¿Qué acción demuestra solidaridad?', 'Ejemplo', 'ayudar a quien lo necesita', ['ayudar a quien lo necesita','esconder materiales','burlarse','dejar basura'], 'La solidaridad implica apoyar a otras personas.'),
    q('¿Qué debemos hacer con las diferencias entre personas?', 'Convivencia', 'respetarlas', ['respetarlas','usarlas para discriminar','burlarnos','ocultarlas siempre'], 'Las diferencias forman parte de la diversidad y deben respetarse.'),
    q('¿Qué es participar?', 'Ciudadanía', 'aportar ideas y acciones en decisiones compartidas', ['aportar ideas y acciones en decisiones compartidas','hacer siempre lo que uno quiere','no escuchar a nadie','evitar toda responsabilidad'], 'Participar permite aportar a la vida de un grupo o comunidad.'),
    q('¿Qué acción cuida el bien común?', 'En una plaza', 'usar los basureros', ['usar los basureros','rayar los juegos','romper plantas','dejar residuos'], 'Usar los basureros ayuda a mantener limpio un espacio compartido.'),
    q('¿Qué hacemos si una norma nos parece injusta?', 'Convivencia democrática', 'expresar la opinión con respeto y dialogar', ['expresar la opinión con respeto y dialogar','agredir','romper todo','amenazar'], 'Se puede expresar desacuerdo de forma respetuosa y buscar cambios por vías adecuadas.'),
    q('¿Por qué es importante escuchar a otros?', 'Participación', 'porque ayuda a comprender distintos puntos de vista', ['porque ayuda a comprender distintos puntos de vista','porque elimina todos los desacuerdos','porque obliga a pensar igual','porque evita aprender'], 'Escuchar permite comprender mejor a otras personas.'),
  ],
};
function buildCards(){els.grid.innerHTML='';topics.forEach(topic=>{const b=document.createElement('button');b.type='button';b.className='english-topic-card';b.innerHTML=`<span class="english-topic-icon" aria-hidden="true">${topic.icon}</span><span class="english-topic-copy"><strong>${topic.title}</strong><small>${topic.subtitle}</small></span><span class="english-topic-status">Practicar →</span>`;b.addEventListener('click',()=>startSession(topic.key));els.grid.appendChild(b);});}
function bankFor(topic){if(topic==='review')return[...banks.maps,...banks.climate,...banks.ancient,...banks.society,...banks.citizenship];return banks[topic]||banks.maps;}
function sessionQuestions(topic){const bank=shuffle(bankFor(topic));const out=[];for(let i=0;i<SESSION_LENGTH;i++){const source=bank[i%bank.length];out.push({...source,id:`his-${Date.now()}-${++serial}`,options:shuffle(source.options)});}return out;}
function startSession(topic){state.topic=topic;state.questionIndex=0;state.currentQuestionId=null;state.score=0;state.streak=0;state.attempts=0;state.answered=false;state.processing=false;state.questions=sessionQuestions(topic);const info=topics.find(t=>t.key===topic)||topics[0];els.modeLabel.textContent=info.title;show(els.quiz);renderQuestion();}
function current(){return state.questions[state.questionIndex]||null;}
function isCurrent(id){const c=current();return Boolean(c&&c.id===id&&state.currentQuestionId===id);}
function renderQuestion(){const c=current();if(!c){finishSession();return;}state.currentQuestionId=c.id;state.attempts=0;state.answered=false;state.processing=false;els.counter.textContent=`${state.questionIndex+1} / ${SESSION_LENGTH}`;els.prompt.textContent=c.prompt;els.question.textContent=c.display;els.question.classList.toggle('reading',c.reading||String(c.display).length>80);els.streak.textContent=String(state.streak);els.answers.innerHTML='';els.feedback.innerHTML='';els.feedback.className='feedback';els.next.classList.add('hidden');c.options.forEach(option=>{const b=document.createElement('button');b.type='button';b.className='answer-button';b.textContent=option;b.dataset.value=option;b.dataset.questionId=c.id;b.addEventListener('click',()=>answer(c.id,option,b));els.answers.appendChild(b);});}
function feedback(kind,title,text,answer=''){els.feedback.className=`english-feedback-card ${kind}`;els.feedback.innerHTML=`<strong class="english-feedback-title">${title}</strong><p class="english-feedback-text">${text}</p>${answer?`<div class="english-feedback-answer">${answer}</div>`:''}`;}
function finishAnswer(id){if(!isCurrent(id))return;const c=current();state.answered=true;[...els.answers.querySelectorAll('.answer-button')].forEach(b=>{b.disabled=true;if(b.dataset.questionId===id&&b.dataset.value===c.correct)b.classList.add('correct');});progress.bestStreak=Math.max(progress.bestStreak,state.streak);saveProgress();els.streak.textContent=String(state.streak);els.next.textContent=state.questionIndex===SESSION_LENGTH-1?'Ver resultado 🌟':'Siguiente →';els.next.classList.remove('hidden');}
function answer(id,value,button){if(state.processing||state.answered||button.disabled||!isCurrent(id)||button.dataset.questionId!==id)return;state.processing=true;try{const c=current();if(String(value)===c.correct){button.classList.add('correct');state.score++;state.streak++;progress.stars++;feedback('success',state.attempts===1?'🌟 ¡Muy bien!':state.streak>=3?'🔥 ¡Excelente racha!':'✨ ¡Muy bien!',c.explanation,c.correct);finishAnswer(id);return;}button.classList.add('wrong');button.disabled=true;if(state.attempts===0){state.attempts=1;feedback('','💡 Una pista fácil',c.explanation,`Busca: ${c.correct}`);return;}state.attempts=2;state.streak=0;feedback('gentle','🌷 Miremos la respuesta',c.explanation,c.correct);finishAnswer(id);}finally{state.processing=false;}}
function next(){if(!state.answered||state.processing)return;state.answered=false;state.currentQuestionId=null;if(state.questionIndex<SESSION_LENGTH-1){state.questionIndex++;renderQuestion();}else finishSession();}
function finishSession(){const info=topics.find(t=>t.key===state.topic)||topics[0];progress.sessions++;progress.byTopic[state.topic]=(Number(progress.byTopic[state.topic])||0)+1;saveProgress();els.finalScore.textContent=String(state.score);if(state.score>=9){els.resultEmoji.textContent='🏆';els.resultTitle.textContent='¡Excelente!';els.resultText.textContent=`Dominaste ${info.title.toLowerCase()}.`;}else if(state.score>=7){els.resultEmoji.textContent='🌟';els.resultTitle.textContent='¡Muy buen trabajo!';els.resultText.textContent=`Vas muy bien en ${info.title.toLowerCase()}.`;}else if(state.score>=5){els.resultEmoji.textContent='💪';els.resultTitle.textContent='¡Buen entrenamiento!';els.resultText.textContent='Una práctica corta más ayudará a fijarlo.';}else{els.resultEmoji.textContent='🌱';els.resultTitle.textContent='Seguimos aprendiendo';els.resultText.textContent='Mirar la pista y corregir también es aprender.';}show(els.result);}
function registerSW(){if(!('serviceWorker'in navigator))return;window.addEventListener('load',async()=>{try{const r=await navigator.serviceWorker.register('./sw.js');r.update().catch(()=>{});}catch{}});}
function init(){assertElements();buildCards();renderProgress();els.back.addEventListener('click',()=>show(els.home));els.next.addEventListener('click',next);els.again.addEventListener('click',()=>startSession(state.topic));els.homeButton.addEventListener('click',()=>show(els.home));registerSW();document.documentElement.dataset.appVersion=HISTORY_VERSION;}
try{init();}catch(error){console.error('No se pudo iniciar Historia',error);}
